// <auto-generated />
namespace Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V56 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V56));
        
        string IMigrationMetadata.Id
        {
            get { return "202007261025489_V56"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
